//
//  FilterEnum.h
//  FilterShowcase
//
//  Created by apple on 12-5-11.
//  Copyright (c) 2012年 Cell Phone. All rights reserved.
//

#ifndef FilterShowcase_FilterEnum_h
#define FilterShowcase_FilterEnum_h

#define FRAME_NUM 5
#define MASK_NUM 5

typedef enum {
    MIC_LENS = 0,
    MIC_USTOON = 1,
    MIC_MARK = 2,
    MIC_SKETCH = 3,
    MIC_PAINT = 4,
    MIC_DRYINK = 5,
    MIC_GOUACHE = 6,
    MIC_WATERCOLOR = 7,
    MIC_OILPAINTING = 8,
    MIC_BEAUTY = 9,
    MIC_PRO = 10,
    MIC_LOFI = 11,
    MIC_HDR = 12,
    MIC_EREBUSNIGHT = 13,
    MIC_SELFPHOTO = 14, 
    MIC_LITTLESUNSHINE = 15,
    MIC_HEFE = 16,
    MIC_NASHVILLE = 17,
    MIC_EARLYBIRD = 18,
    MIC_RISE = 19,
    MIC_AMARO = 20,
    MIC_LAKE = 21,
    MIC_TOASTER = 22,
    SHARE_FILM1 = 23,
    MIC_ANSEL = 24,
    MIC_DIANA = 25,
    MIC_1977 = 26,
    MIC_COUNTRY = 27,
    MIC_INKWELL = 28,

    MIC_CARTOON0 = 29,
    MIC_CARTOON1 = 30,
    MIC_CARTOON2 = 31,
    MIC_CARTOON3 = 32,
    MIC_CARTOON4 = 33,
    MIC_CARTOON5 = 34,
    MIC_CARTOON6 = 35,
    MIC_PRINT = 36,

    MIC_XPRO = 37,
    MIC_GRAY = 38,
    MIC_LOMO = 39,
    MIC_INSTANT = 40,
    MIC_HUDSON = 41,
    MIC_KELVIN = 42,
    MIC_SIERRA = 43,
    MIC_SUTRO = 44,
    MIC_VALENCIA = 45,
    MIC_CRAYON = 46,
    MIC_THOSE_YEAR = 47,
    MIC_WETINK = 48,
    SHARE_FISHEYE = 49,
    SHARE_LAPLACIAN = 50,

    WEICO_FILM = 51, 
    WEICO_DIANA = 52, 
    WEICO_BW = 53, 
    WEICO_VIOLET = 54, 
    WEICO_1949 = 55, 
    WEICO_LOFT = 56, 
    WEICO_HOLGA = 57, 
    WEICO_FOREST = 58,
    WEICO_OLDSCHOOL = 59, 
    WEICO_INSTANT = 60, 
    WEICO_SUN = 61, 
    WEICO_LONDON = 62, 
    WEICO_INDIGO = 63, 
    WEICO_SILVER = 64, 
    WEICO_MOMENT = 65, 
    QQ_ROWFILM = 66,
    QQ_TONNYBW = 67, 
    QQ_TONNYNOSTALGIC = 68,
    QQ_TONNYPHANTASY = 69, 
    QQ_TONNYSOFT = 70, 
    QQ_TONNYPRO = 71, 
    QQ_TONNYCHURCH = 72,
    AVG_ROUND_FILTER = 73,
    MIC_HDR_HSV = 74,
    MIC_CARTOON4_PREVIEW = 75,
    MIC_CARTOON5_PREVIEW = 76,
    MIC_FACEBEAUTIFY_0 = 77, 
    MIC_FACEBEAUTIFY_1 = 78,
    MIC_OILPAINTING_PREVIEW = 79,
    MIC_OILPAINTING_1 = 80,
    MIC_NEWSKETCH = 81,

    MIC_MIRROR = 82,
    MIC_TIMECHANNEL = 83,
    MIC_TWIRL = 84,
    
    MIC_Portait0 = 85,
    MIC_Portait1 = 86,
    MIC_Portait2 = 87,
    MIC_Portait3 = 88,
    MIC_Portait4 = 89,
    MIC_AVG_ROUND = 90,
    MR_GaussEX = 91,
    
    MR_COLORPENCIL_LOW = 92,
    MR_COLORPENCIL = 93,
    MR_GaussMOMENTEX = 94,
    MIC_MARK_FORSAVE = 95,
    MIC_AUTO = 96,
    MIC_COLOR_RED = 97,
    MIC_COLOR_ORANGE = 98,
    MIC_COLOR_YELLOW = 99,
    MIC_COLOR_GREEN = 100,
    MIC_COLOR_CYAN = 101,
    MIC_COLOR_BLUE = 102,
    MIC_COLOR_PURPLE = 103,
    
    MIC_INK = 104,
    MIC_COLOR_INK = 105,
    MIC_MANGA_LOW = 106,
    MIC_MANGA = 107,
    MIC_NEWPRINT_0 = 108,
    MIC_NEWPRINT_1 = 109,
    MIC_NEWPRINT_2 = 110,
// 1.5
    MIC_MOSAIC,
    MIC_KALEIDOSCOPE,
    MIC_ABAO,
    MIC_WARM = 114,
    MIC_MANGASAVE,
    MIC_ABAO_SMOOTH = 116,
//gpu  
    MIC_ORIENTATION = 117,
    MIC_Alpha  = 118,
    MIC_GrayOval = 119,
    MIC_GrayParallel = 120,
    MIC_GrayRound = 121,
//end
    MIC_NEWABAO = 122,
//cpu
    MIC_Poster = 124,
//end
    MIC_EXPOSURE = 125,
    MIC_WALDEN = 126, //同桌的你
    MIC_BRANNAN = 127, //宝丽来
    MIC_JINGWU1 = 128,
    MIC_Portait5 = 129,
    MIC_NIGHTLEVEL = 130,
    MIC_GLOW = 131,
    MIC_CPUEXPOSURE = 132,
    MIC_Portait0_Low = 133,
    MIC_Portait1_Low = 134,
    MIC_Portait2_Low = 135,
    MIC_Portait3_Low = 136,
    MIC_Portait4_Low = 137,
    MIC_Portait5_Low = 138,
    MIC_GLOW_Low = 139,
    MIC_Portait6 = 140,
    MIC_Portait6_Low = 141,
    MIC_JINGWU1_Low = 142,
    MIC_Portait0_Lower = 143,
    MIC_Portait1_Lower = 144,
    MIC_Portait2_Lower = 145,
    MIC_Portait3_Lower = 146,
    MIC_Portait4_Lower = 147,
    MIC_Portait5_Lower = 148,
    MIC_Portait6_Lower = 149,
    MIC_LOMOFILM = 150,
    MIC_Portait7 = 151,
    MIC_Portait7_Low = 152,
    MIC_Portait7_Lower = 153,
    MIC_Bokeh = 154,
    MIC_Sharpen = 155,
    MIC_Flares = 156,
    MIC_Portait0_NB = 157,
    MIC_Portait1_NB = 158,
    MIC_Portait2_NB = 159,
    MIC_Portait3_NB = 160,
    MIC_Portait4_NB = 161,
    MIC_Portait5_NB = 162,
    MIC_Portait6_NB = 163,
    MIC_Portait7_NB = 164,
    MIC_BEAUTY_NB = 165,
    MIC_Portait3_For_ShuiYin = 166,
    MIC_Portait_HongRun = 167,
    MIC_Portait_TianMei = 168,
    MIC_Portait_YangGuang = 169,
    MIC_Portait_HongRun_NB = 170,
    MIC_Portait_TianMei_NB = 171,
    MIC_Portait_YangGuang_NB = 172,
    MIC_Portait2_For_ShuiYin = 173,
    MIC_Alpha_Revert = 174,
    MIC_Denoise = 175,
    MIC_Dehaze = 176,
    MIC_Montage = 177,
    MIC_Smart_Sharpen = 178,
    MIC_LSS_Up_2_3 = 179,
    MIC_LSS_Up_3_4 = 180,
    MIC_LSS_Down_2_3 = 181,
    MIC_LSS_Down_3_4 = 182,
    MIC_LSS_Up_2_3_Add_Residual = 183,
    MIC_LSS_SEARCH_POINT = 184,
    MIC_LSS_RGB2YUV = 185,
    MIC_LSS_YUV2RGB = 186,
    MIC_LSS_Up_2_3_OnlyR = 187,
    MIC_LSS_Up_3_4_OnlyR = 188,
    MIC_LSS_Down_2_3_OnlyR = 189,
    MIC_LSS_Down_3_4_OnlyR = 190,
    MIC_Sharpen2 = 191,
    MIC_ALPHA_MIX = 192,
    MIC_BICUBIC = 193,
    MIC_SR_LSS = 194,
    MIC_ALPHA_ADJUST = 195,
    MIC_OILPAINTING_PORTRAIT = 196,
    MIC_OILPAINTING_PORTRAIT_1 = 197,
    MIC_FACEBEAUTY_PLUS_FILTER = 198,
    MIC_LENSFLARE = 199,
    MIC_GLOW_CPU_FILTER = 200,
    MIC_FACEBEAUTY_FILTER = 201,
    MIC_DETAIL_ENHANCE = 202,
    MIC_STIPPLING = 203,
    
    MIC_PTU_FILTER = 204,
    MIC_PTU_SHISHANG_SH = MIC_PTU_FILTER,
    MIC_PTU_FUGU_SH = MIC_PTU_SHISHANG_SH + 1,
    MIC_PTU_COLOR_SH = MIC_PTU_FUGU_SH + 1,
    MIC_PTU_FEN = MIC_PTU_COLOR_SH + 1,
    MIC_PTU_FUGUHUANG = MIC_PTU_FEN + 1,
    MIC_PTU_GOGUANGLANZI = MIC_PTU_FUGUHUANG + 1,
    MIC_PTU_HEIBAI = MIC_PTU_GOGUANGLANZI + 1,
    MIC_PTU_HUAIJIU = MIC_PTU_HEIBAI + 1,
    MIC_PTU_JIAOPIAN = MIC_PTU_HUAIJIU + 1,
    MIC_PTU_LAN = MIC_PTU_JIAOPIAN + 1,
    MIC_PTU_LANTUISE = MIC_PTU_LAN + 1,
    MIC_PTU_MOLV = MIC_PTU_LANTUISE + 1,
    MIC_PTU_NUANHUANG = MIC_PTU_MOLV + 1,
    MIC_PTU_DRAMA = MIC_PTU_NUANHUANG + 1,
    MIC_PTU_FEN2 = MIC_PTU_DRAMA + 1,
    MIC_PTU_HEIBAI2 = MIC_PTU_FEN2 + 1,
    MIC_PTU_NIGHT = MIC_PTU_HEIBAI2 + 1,
    MIC_PTU_MAYFAIR = MIC_PTU_NIGHT + 1,
    MIC_PTU_HEIBAI3 = MIC_PTU_MAYFAIR + 1,
    MIC_PTU_FUGU = MIC_PTU_HEIBAI3 + 1,
    MIC_PTU_DRAMA2 = MIC_PTU_FUGU + 1,
    MIC_PTU_SNOW = MIC_PTU_DRAMA2 + 1,
    MIC_PTU_GAOLENG = MIC_PTU_SNOW + 1,
    
    MIC_QQ_FILTER = 300,
    MIC_QQ_INSTANT = MIC_QQ_FILTER,
    MIC_QQ_AMARO = MIC_QQ_INSTANT + 1,
    MIC_QQ_TianMei = MIC_QQ_AMARO + 1,
    
    GPUIMAGE_NUMFILTERS
} GPUImageShowcaseFilterType;

#endif
